POST http://localhost:3001/api/blogs/
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJoYW5kbGVyQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3ODE3NzU0MzR9.oqrNPKlKY4pSJ3zb-LyUad5LrQvj-3CE6t2qYaZsqGk

{
    "author": "Unknown",
    "url": "http://localhost/",
    "title": "Blog by non user"
}

###

DELETE http://localhost:3001/api/blogs/5
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJoYW5kbGVyQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3ODE3NzU0MzR9.oqrNPKlKY4pSJ3zb-LyUad5LrQvj-3CE6t2qYaZsqGk

###

PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
    "likes": 3
}

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "name": "twobert",
    "username": "rhandler@gmail.com" 
}

###

PUT http://localhost:3001/api/users/secret/
Content-Type: application/json

{
    "name": "Matti Luukk"
}

###

POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "rhandler@gmail.com",
    "password": "secret"
}