POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "author": "another anon",
    "url": "http://localhost/",
    "title": "Blog through web"
}

###

DELETE http://localhost:3001/api/blogs/3

###

PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
    "likes": 3
}

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "name": "twobert",
    "username": "rhandler@gmail.com" 
}

###

PUT http://localhost:3001/api/users/secret/
Content-Type: application/json

{
    "name": "Matti Luukk"
}